/* ---------------------------------------------------- */
/*  Generated by Enterprise Architect Version 12.1 		*/
/*  Created On : 29-Jun-2017 4:51:37 PM 				*/
/*  DBMS       : MySql 						*/
/* ---------------------------------------------------- */

SET FOREIGN_KEY_CHECKS=0 
;

/* Drop Tables */

DROP TABLE IF EXISTS `groups` CASCADE
;

DROP TABLE IF EXISTS `m2m_user_groups` CASCADE
;

DROP TABLE IF EXISTS `roles` CASCADE
;

DROP TABLE IF EXISTS `users` CASCADE
;

/* Create Tables */

CREATE TABLE `groups`
(
	`g_id` INT NOT NULL AUTO_INCREMENT,
	`g_name` VARCHAR(100) NOT NULL,
	CONSTRAINT `PK_groups` PRIMARY KEY (`g_id` ASC)
)

;

CREATE TABLE `m2m_user_groups`
(
	`ug_id` INT NOT NULL AUTO_INCREMENT,
	`u_id` INT NOT NULL,
	`g_id` INT NOT NULL,
	CONSTRAINT `PK_m2m_user_groups` PRIMARY KEY (`ug_id` ASC)
)

;

CREATE TABLE `roles`
(
	`r_id` INT NOT NULL AUTO_INCREMENT,
	`r_name` VARCHAR(50) NOT NULL,
	CONSTRAINT `PK_roles` PRIMARY KEY (`r_id` ASC)
)

;

CREATE TABLE `users`
(
	`u_id` INT NOT NULL AUTO_INCREMENT,
	`u_login` VARCHAR(100) NOT NULL,
	`u_password` VARCHAR(40) NOT NULL,
	`u_name` VARCHAR(100) NOT NULL,
	`u_lastname` VARCHAR(100) NOT NULL,
	`email` VARCHAR(100) NOT NULL,
	`r_id` INT NOT NULL,
	CONSTRAINT `PK_users` PRIMARY KEY (`u_id` ASC)
)

;

/* Create Primary Keys, Indexes, Uniques, Checks */

ALTER TABLE `groups` 
 ADD CONSTRAINT `UNQ_g_name` UNIQUE (`g_name` ASC)
;

ALTER TABLE `m2m_user_groups` 
 ADD INDEX `IXFK_m2m_user_groups_groups` (`g_id` ASC)
;

ALTER TABLE `m2m_user_groups` 
 ADD INDEX `IXFK_m2m_user_groups_users` (`u_id` ASC)
;

ALTER TABLE `roles` 
 ADD CONSTRAINT `UNQ_r_name` UNIQUE (`r_name` ASC)
;

ALTER TABLE `users` 
 ADD CONSTRAINT `UNQ_u_login` UNIQUE (`u_login` ASC)
;

ALTER TABLE `users` 
 ADD CONSTRAINT `UNQ_u_name` UNIQUE (`u_name` ASC)
;

ALTER TABLE `users` 
 ADD CONSTRAINT `UNQ_u_lastname` UNIQUE (`u_lastname` ASC)
;

ALTER TABLE `users` 
 ADD CONSTRAINT `UNQ_u_email` UNIQUE (`email` ASC)
;

ALTER TABLE `users` 
 ADD INDEX `IXFK_users_roles` (`r_id` ASC)
;

/* Create Foreign Key Constraints */

ALTER TABLE `m2m_user_groups` 
 ADD CONSTRAINT `FK_m2m_user_groups_groups`
	FOREIGN KEY (`g_id`) REFERENCES `groups` (`g_id`) ON DELETE Cascade ON UPDATE Cascade
;

ALTER TABLE `m2m_user_groups` 
 ADD CONSTRAINT `FK_m2m_user_groups_users`
	FOREIGN KEY (`u_id`) REFERENCES `users` (`u_id`) ON DELETE Cascade ON UPDATE Cascade
;

ALTER TABLE `users` 
 ADD CONSTRAINT `FK_users_roles`
	FOREIGN KEY (`r_id`) REFERENCES `roles` (`r_id`) ON DELETE Cascade ON UPDATE Cascade
;

SET FOREIGN_KEY_CHECKS=1 
;
